on:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    steps:
      - run: |
          release_note=$(curl -X POST -H 'Accept: application/vnd.github.v3+json' -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/${{ github.repository }}/releases/generate-notes -d '{"tag_name":"v1", "previous_tag_name":"v0"}' | jq -r .body | sed 's/\\n/\n/g')
          echo "$release_note"
          printf -v formatted_note "%b" "$release_note"
          echo "********************************************"
          echo "$formatted_note"
          echo "release_note=$formatted_note" >> $GITHUB_ENV
      - run: echo ${{ env.release_note }}
